fix: Correct SpeechSynthesisUtterance syntax error in SkiFree easter egg
Fixed typo: 'SpeechSynthesis Utterance' -> 'SpeechSynthesisUtterance'
This was causing home tab content to fail loading due to JavaScript syntax error.

Error: Uncaught SyntaxError: Unexpected identifier 'Utterance'
Location: gui/index.html line 3500